### ISSUE TITLE
Add contributing.md file please.

### ISSUE THREAD

**Issue by rahulatrkm** [devfolioco/devfolio-gatsby-starter#43]
I don't see any contributing instructions here. Can anyone please add it so that it will easy for follow up?

**Comment by rahulatrkm** [comment]
Also please add what is the end product of this project. I don't see proper documentation. If it is available please let me know where I can find it. Thank you.

**Comment by michizhou** [comment]
@ajayns If you think a contributing.md with instructions would be helpful, I could start working on drafting one up for this repo. Feel free to let me know about any important steps/instructions I should include if you give the go-ahead.

**Comment by ajayns** [comment]
@rahulatrkm Hey! This is not an end product, but rather a starting point. It aims to provide a basic setup using Gatsby to kickstart static site development, while also providing commonly used components such as FAQs or gallery. So we don't have a roadmap for this to reach a product endpoint, but rather are always up for improving the starter so as to accommodate commonly used functionalities while still keeping it lightweight and not cramped. 

@michizhou Since there are downsides in having one and we've had lot of attention as of late, you could go ahead and try to make one. Maybe take reference from other Gatsby starters and also might wanna mention we use Prettier for code formatting.
